### ISSUE TITLE
Criar "mockup" para a aplicação

### ISSUE THREAD

**Issue by gregori** [jeanloose/PONG#3]
Criar um "mockup" para a aplicação (pode ser desenho à mão, mas deve ser feito upload para o repositório) com as possiveis telas

**Comment by andersonfrarecatolica** [comment]
![fase_campo](https://cloud.githubusercontent.com/assets/20805251/23880741/5875083c-0834-11e7-8354-c26d458e3d48.jpg)
![fase_praia](https://cloud.githubusercontent.com/assets/20805251/23880740/58750c4c-0834-11e7-99ef-8ac5058079c1.jpg)

**Comment by andersonfrarecatolica** [comment]
![fase_campo](https://cloud.githubusercontent.com/assets/20805251/23880799/d49f7366-0834-11e7-9a83-bc075237e4d5.jpg)

**Comment by andersonfrarecatolica** [comment]
![fase_campo](https://cloud.githubusercontent.com/assets/20805251/23880946/c047c458-0835-11e7-90d2-6fea816378a1.jpg)
![fase_praia](https://cloud.githubusercontent.com/assets/20805251/23880945/c045aea2-0835-11e7-93fe-77855a50b8a0.jpg)
