### ISSUE TITLE
Estudar Canvas/JS

### ISSUE THREAD

**Issue by gregori** [jeanloose/PONG#5]
Preparar um estudo sobre Canvas/JS
Definição de pronto: artigo escrito (pode ser em Markdown, com commit no repositório)

**Comment by camilamaas** [comment]
Canvas é um elemento HTML que pode ser usado para desenhar gráficos, fazer composições de fotos ou animações, por exemplo, utilizando scripts. 
A janela do Canvas pode ser criada através da linha de comando abaixo (dentro do próprio HTML):
<canvas id='tela' width="600" height='400'></canvas> 

O canvas é baseado em coordenadas X e Y (x = horizontal e y = vertical).

Para começar a "desenhar" no canvas é necessário abrir a tag  <script> e dentro dela seu elemento e o contexto, como mostram as linhas abaixo
var tela = document.getElementById("tela");
var pincel = tela.getContext("2d")

pincel.fillStyle="green" - A linha abaixo define a cor que será utilizada para desenhar

fillRect(x, y, w, h) -  define em qual medida do eixo X e Y o desenho começará, qual sua largura (W) e qual sua altura (H).
