### ISSUE TITLE
Estudar CSS

### ISSUE THREAD

**Issue by gregori** [jeanloose/PONG#6]
Preparar um estudo sobre CSS3
Definição de pronto: artigo escrito (pode ser em Markdown, com commit no repositório)

**Comment by isaminel** [comment]
O CSS (Cascading Style Sheets) é uma folha de estilo composta por camadas, usada para definir a aparência de páginas que possuem em seu desenvolvimento linguagens de marcação (XML, HTML e XHTML). O CSS define como serão exibidos os elementos contidos no código de uma página da e sua maior vantagem é efetuar a separação entre o formato e o conteúdo de um documento.

**Comment by isaminel** [comment]
O CSS (Cascading Style Sheets) é uma folha de estilo composta por camadas, usada para definir a aparência de páginas que possuem em seu desenvolvimento linguagens de marcação (XML, HTML e XHTML). O CSS define como serão exibidos os elementos contidos no código de uma página da e sua maior vantagem é efetuar a separação entre o formato e o conteúdo de um documento.

Devido a evolução dos recursos de programação, as páginas da internet estavam adotando cada vez mais estilos e variações para deixá-las mais elegantes e atrativas para os usuários. Foram criadas novas tags e atributos de estilo para o HTML e ele passou a exercer tanto a função de estruturar o conteúdo quanto de apresentá-lo para o usuário final. Entretanto, isto começou a trazer um problema para os desenvolvedores, pois não havia uma forma de definir, por exemplo, um padrão para todos os cabeçalhos ou conteúdos em diversas páginas. Ou seja, as alterações teriam que ser feitas manualmente, uma a uma.

A partir destas complicações, nasceu o CSS. Inicialmente, foi desenvolvido para habilitar a separação do conteúdo e formato de um documento de sua apresentação, incluindo elementos como cores, formatos de fontes e layout. Esta separação proporcionou uma maior flexibilidade e controle na especificação de como as características serão exibidas, permitiu um compartilhamento de formato e reduziu a repetição no conteúdo estrutural de uma página.

Um exemplo de código em CSS:

body {
    background-color: lightblue;
}

h1 {
    color: white;
    text-align: center;
}

p {
    font-family: verdana;
    font-size: 20px;
}

![dfs](https://cloud.githubusercontent.com/assets/20672524/23881089/d2dd5dca-0836-11e7-8e55-b2fccc7e3fcd.png)

**Comment by isaminel** [comment]
![dfs](https://cloud.githubusercontent.com/assets/20672524/23881082/bf060522-0836-11e7-8209-91e42ca63892.png)
