### ISSUE TITLE
Estudar JavaScript

### ISSUE THREAD

**Issue by gregori** [jeanloose/PONG#7]
Preparar um estudo sobre JavaScript
Definição de pronto: artigo escrito (pode ser em Markdown, com commit no repositório)

**Comment by julianascimento** [comment]
Javascript é uma linguagem utilizada para determinar a movimentação dentro do HTML ou Web, ela é utilizada para controlar o HTML e o CSS manipulando os comportamentos na página. 

- Para utilizar o Javascript dentro do código HTML é preciso colocar o código abaixo dentro do Body:<script type="text/javascript">//Comandos do Javascript//</script>

- Se quiser adicionar um código de javascript externo ao código de HTML coloque esse código no Body:<script type="text/javascript" src="js/nome-arquivo.js"></script>
